version: '3.8'

services:
  read-back:
    build: ./wn-jjklrt-read/back
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: worldnews_db_writer
      DB_PORT: 5432
      DB_USER: julie
      DB_PASSWORD: louvre
      DB_NAME: worldnews_db_writer
    depends_on:
      - worldnews_db_writer

  read-front:
    build: ./wn-jjklrt-read/front
    ports:
      - "3010:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://read-back:3001
    depends_on:
      - read-back

  write-back:
    build: ./wn-jjklrt-write/write-back
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      PORT: 3002
      DB_HOST: worldnews_db_writer
      DB_PORT: 5432
      DB_USER: julie
      DB_PASSWORD: louvre
      DB_NAME: worldnews_db_writer
    depends_on:
      - worldnews_db_writer

  write-front:
    build: ./wn-jjklrt-write/write-front
    ports:
      - "3020:3000"
    environment:
      NODE_ENV: production
      # NEXT_PUBLIC_API_URL: http://write-back:3002
    depends_on:
      - write-back

  worldnews_db_writer:
    image: postgres:15
    environment:
      POSTGRES_USER: julie
      POSTGRES_PASSWORD: louvre
      POSTGRES_DB: worldnews_db_writer
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
