version: '3.8'

services:
  read-back:
    build: ./wn-jjklrt-read/back
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production

  read-front:
    build: ./wn-jjklrt-read/front
    ports:
      - "3010:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://read-back:3001
    depends_on:
      - read-back

  write-back:
    build: ./wn-jjklrt-write/write-back
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production

  write-front:
    build: ./wn-jjklrt-write/write-front
    ports:
      - "3020:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://write-back:3002
    depends_on:
      - write-back
